name: Alerta de push a main

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a ntfy.sh
        run: |
          curl -d "¡Nuevo push a main en el repositorio!" ntfy.sh/devops-itla
